# Generated by Django 4.2.2 on 2023-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('desc', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
